In [1]:
#NumPy Crash Course

#define an array
import numpy
mylist = [1, 2, 3]
myarray = numpy.array(mylist)
print(myarray)
print(myarray.shape)


[1 2 3]
(3,)


In [2]:
#access values
mylist = [[1, 2, 3], [4, 5, 6]]
myarray = numpy.array(mylist)
print(myarray)
print(myarray.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [3]:
print("First row: %s" % myarray[0])
print("Last row: %s" % myarray[-1])

First row: [1 2 3]
Last row: [4 5 6]


In [4]:
print("Specific row and col: %s" % myarray[0, 2])
print("Whole col: %s" % myarray[:, 2])

Specific row and col: 3
Whole col: [3 6]


In [5]:
#Arithmetic
myarray1 = numpy.array([2, 2, 2])
myarray2 = numpy.array([3, 3, 3])
print("Addition: %s" % (myarray1 + myarray2))
print("Multiplication: %s" % (myarray1 * myarray2))

Addition: [5 5 5]
Multiplication: [6 6 6]
